name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install pylint
        pip3 install -r requirements.txt
        python3 setup.py install
    - name: Analysing the code with pylint
      run: |
        python3 tests/test.py
        pylint `ls -R|grep .py$|xargs`
